const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "94724831809" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "94771810698";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "94724831809";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "true"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "ZANTA_MD",
  ownername:process.env.OWNER_NAME|| "ZANTA_MD",

  sessionName:process.env.SESSION_ID || "SUHAIL_06_07_02_21_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTY4LFxuICAgICAgICA3LFxuICAgICAgICA0MCxcbiAgICAgICAgMjgsXG4gICAgICAgIDIyMCxcbiAgICAgICAgNjQsXG4gICAgICAgIDEyMixcbiAgICAgICAgMjI5LFxuICAgICAgICAyNTUsXG4gICAgICAgIDIxNixcbiAgICAgICAgMTg5LFxuICAgICAgICAyMTMsXG4gICAgICAgIDMsXG4gICAgICAgIDc5LFxuICAgICAgICAxNzIsXG4gICAgICAgIDEsXG4gICAgICAgIDM1LFxuICAgICAgICAxMTgsXG4gICAgICAgIDIyNixcbiAgICAgICAgMjksXG4gICAgICAgIDIxNixcbiAgICAgICAgMTMwLFxuICAgICAgICAyMDEsXG4gICAgICAgIDE0MixcbiAgICAgICAgMTQ2LFxuICAgICAgICAxNDQsXG4gICAgICAgIDEzLFxuICAgICAgICAxMjEsXG4gICAgICAgIDcyLFxuICAgICAgICAxNzEsXG4gICAgICAgIDI0OSxcbiAgICAgICAgMTA4XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI0NSxcbiAgICAgICAgMTUzLFxuICAgICAgICA4MixcbiAgICAgICAgMTIxLFxuICAgICAgICA3OSxcbiAgICAgICAgMjksXG4gICAgICAgIDg4LFxuICAgICAgICAxMTgsXG4gICAgICAgIDE2LFxuICAgICAgICAzNSxcbiAgICAgICAgNjcsXG4gICAgICAgIDIwMSxcbiAgICAgICAgODIsXG4gICAgICAgIDg1LFxuICAgICAgICA0OCxcbiAgICAgICAgMTU4LFxuICAgICAgICAyNDMsXG4gICAgICAgIDE0NixcbiAgICAgICAgMjI1LFxuICAgICAgICAyMTksXG4gICAgICAgIDIwNyxcbiAgICAgICAgMTA1LFxuICAgICAgICA3MSxcbiAgICAgICAgMTcsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMTQwLFxuICAgICAgICA1OCxcbiAgICAgICAgMTYyLFxuICAgICAgICAyMDIsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTQsXG4gICAgICAgIDMwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMTYsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMjA2LFxuICAgICAgICAxNDIsXG4gICAgICAgIDUwLFxuICAgICAgICAyMSxcbiAgICAgICAgNDcsXG4gICAgICAgIDE5NSxcbiAgICAgICAgMTEzLFxuICAgICAgICA0NyxcbiAgICAgICAgMTEsXG4gICAgICAgIDIwNyxcbiAgICAgICAgOTAsXG4gICAgICAgIDI0LFxuICAgICAgICAxMDIsXG4gICAgICAgIDk3LFxuICAgICAgICAxNzYsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTg5LFxuICAgICAgICAzNyxcbiAgICAgICAgMTA3LFxuICAgICAgICA3MCxcbiAgICAgICAgMjE1LFxuICAgICAgICAzNixcbiAgICAgICAgMTE5LFxuICAgICAgICAyMzcsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMTk1LFxuICAgICAgICA2MixcbiAgICAgICAgMyxcbiAgICAgICAgMTA4LFxuICAgICAgICAxMDZcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTA0LFxuICAgICAgICAxNDQsXG4gICAgICAgIDM3LFxuICAgICAgICA3NSxcbiAgICAgICAgMTk1LFxuICAgICAgICAxOSxcbiAgICAgICAgNSxcbiAgICAgICAgNDQsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMTcsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMTUxLFxuICAgICAgICAxNDQsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMTQzLFxuICAgICAgICA3NyxcbiAgICAgICAgOTksXG4gICAgICAgIDI1MyxcbiAgICAgICAgMTE0LFxuICAgICAgICAxMTAsXG4gICAgICAgIDEyMCxcbiAgICAgICAgNTMsXG4gICAgICAgIDg1LFxuICAgICAgICA0NSxcbiAgICAgICAgNTMsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTg1LFxuICAgICAgICAzNCxcbiAgICAgICAgMTM0LFxuICAgICAgICA5LFxuICAgICAgICAyLFxuICAgICAgICAzMlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTc2LFxuICAgICAgICAyOSxcbiAgICAgICAgMjI2LFxuICAgICAgICAxNzAsXG4gICAgICAgIDMwLFxuICAgICAgICA1MyxcbiAgICAgICAgMjM3LFxuICAgICAgICAxNjYsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMjAwLFxuICAgICAgICAxMzgsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMzksXG4gICAgICAgIDEyOCxcbiAgICAgICAgMzcsXG4gICAgICAgIDMwLFxuICAgICAgICAyMCxcbiAgICAgICAgMTQ5LFxuICAgICAgICA1LFxuICAgICAgICA2LFxuICAgICAgICAxNzYsXG4gICAgICAgIDkzLFxuICAgICAgICAxOTMsXG4gICAgICAgIDIyNSxcbiAgICAgICAgMTksXG4gICAgICAgIDE1NixcbiAgICAgICAgNzcsXG4gICAgICAgIDIwMyxcbiAgICAgICAgOTAsXG4gICAgICAgIDYsXG4gICAgICAgIDI0MixcbiAgICAgICAgOTlcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODEsXG4gICAgICAgIDIwMCxcbiAgICAgICAgOTcsXG4gICAgICAgIDE0NixcbiAgICAgICAgNjQsXG4gICAgICAgIDI0MixcbiAgICAgICAgMjksXG4gICAgICAgIDM3LFxuICAgICAgICAyMzEsXG4gICAgICAgIDk3LFxuICAgICAgICAxMDMsXG4gICAgICAgIDQ3LFxuICAgICAgICAyMjAsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMjE3LFxuICAgICAgICA1LFxuICAgICAgICAyMzYsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMjI5LFxuICAgICAgICAyMzYsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMjM0LFxuICAgICAgICAxODYsXG4gICAgICAgIDI0NyxcbiAgICAgICAgNTEsXG4gICAgICAgIDQ0LFxuICAgICAgICA4MSxcbiAgICAgICAgOTAsXG4gICAgICAgIDU1LFxuICAgICAgICAxODgsXG4gICAgICAgIDUzLFxuICAgICAgICAyN1xuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxOTIsXG4gICAgICAgICAgMTk2LFxuICAgICAgICAgIDEwMSxcbiAgICAgICAgICA5OCxcbiAgICAgICAgICAyNTUsXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgODQsXG4gICAgICAgICAgMjA4LFxuICAgICAgICAgIDE5MyxcbiAgICAgICAgICAxMCxcbiAgICAgICAgICAyNDUsXG4gICAgICAgICAgMjQzLFxuICAgICAgICAgIDE4NyxcbiAgICAgICAgICAxMyxcbiAgICAgICAgICAxMDAsXG4gICAgICAgICAgMjEzLFxuICAgICAgICAgIDE5NCxcbiAgICAgICAgICAxNDYsXG4gICAgICAgICAgMjUsXG4gICAgICAgICAgOTksXG4gICAgICAgICAgMTUyLFxuICAgICAgICAgIDIzNixcbiAgICAgICAgICAxMDgsXG4gICAgICAgICAgMjYsXG4gICAgICAgICAgMTI5LFxuICAgICAgICAgIDkzLFxuICAgICAgICAgIDE0LFxuICAgICAgICAgIDM4LFxuICAgICAgICAgIDE2NixcbiAgICAgICAgICAxNTEsXG4gICAgICAgICAgNjgsXG4gICAgICAgICAgOTNcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNzcsXG4gICAgICAgICAgMTM3LFxuICAgICAgICAgIDQ2LFxuICAgICAgICAgIDI1MyxcbiAgICAgICAgICA2NyxcbiAgICAgICAgICAxMTAsXG4gICAgICAgICAgMTgxLFxuICAgICAgICAgIDE4OCxcbiAgICAgICAgICAxMjcsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDQsXG4gICAgICAgICAgMTExLFxuICAgICAgICAgIDIyNyxcbiAgICAgICAgICA3MixcbiAgICAgICAgICAxNTgsXG4gICAgICAgICAgNzMsXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgMjMsXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDM4LFxuICAgICAgICAgIDEyMyxcbiAgICAgICAgICAyMTAsXG4gICAgICAgICAgMTA3LFxuICAgICAgICAgIDIyMixcbiAgICAgICAgICAyMzAsXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDE2MCxcbiAgICAgICAgICA4MCxcbiAgICAgICAgICAzMSxcbiAgICAgICAgICAxNyxcbiAgICAgICAgICAxNjYsXG4gICAgICAgICAgNjBcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA5OSxcbiAgICAgICAgMTYwLFxuICAgICAgICAxNDYsXG4gICAgICAgIDI0NCxcbiAgICAgICAgODQsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMTYwLFxuICAgICAgICAyMTgsXG4gICAgICAgIDEsXG4gICAgICAgIDg0LFxuICAgICAgICA2NixcbiAgICAgICAgNzEsXG4gICAgICAgIDE2MixcbiAgICAgICAgMTMsXG4gICAgICAgIDQ0LFxuICAgICAgICAyNDMsXG4gICAgICAgIDE5LFxuICAgICAgICAxODYsXG4gICAgICAgIDEzOSxcbiAgICAgICAgOTQsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMTkxLFxuICAgICAgICAzMCxcbiAgICAgICAgMjM0LFxuICAgICAgICA1OCxcbiAgICAgICAgMTIwLFxuICAgICAgICA5MSxcbiAgICAgICAgMTk0LFxuICAgICAgICAxLFxuICAgICAgICAyMzQsXG4gICAgICAgIDE4NSxcbiAgICAgICAgODIsXG4gICAgICAgIDE2NSxcbiAgICAgICAgMjI3LFxuICAgICAgICA5MSxcbiAgICAgICAgMjIyLFxuICAgICAgICA3NCxcbiAgICAgICAgMjA4LFxuICAgICAgICAyNyxcbiAgICAgICAgMjI2LFxuICAgICAgICAxMjcsXG4gICAgICAgIDEyLFxuICAgICAgICAxNDgsXG4gICAgICAgIDE5MixcbiAgICAgICAgMTkwLFxuICAgICAgICAxMSxcbiAgICAgICAgMTMzLFxuICAgICAgICA0MSxcbiAgICAgICAgMTkyLFxuICAgICAgICA0MyxcbiAgICAgICAgMjgsXG4gICAgICAgIDIxLFxuICAgICAgICA2MixcbiAgICAgICAgMTIyLFxuICAgICAgICAyMTcsXG4gICAgICAgIDE0MCxcbiAgICAgICAgNjksXG4gICAgICAgIDE5OSxcbiAgICAgICAgMTAzLFxuICAgICAgICA3MSxcbiAgICAgICAgMTI3LFxuICAgICAgICAxMzksXG4gICAgICAgIDIzLFxuICAgICAgICAxXG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiA4MixcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJQeWYvZWFEWHNxeUNhSGhaTzJRZUJwRXpMbGN2OFVwMnlFMUxtcTR1bkhrPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjk0NzI0ODMxODA5QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI5Q0NBRTE5QjU2RUI1RUQ0RDc1MUVCNTE5RkNDQ0Y1NFwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3NDAxMTgwMTVcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5NDcyNDgzMTgwOUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiQjlENjczNkFCQ0M2MTRFRjZCNjc2MEQwN0JFRkI3NzJcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzQwMTE4MDE1XG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIlZLZlRIYmJyUU9Xb0hzX1pGa3lSYVFcIixcbiAgXCJwaG9uZUlkXCI6IFwiYjc5ODhjODAtODI5YS00OWEzLWExM2ItNzRlZWE4ZDlkMjY3XCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDI1MyxcbiAgICAgIDkzLFxuICAgICAgMjE5LFxuICAgICAgMjQ2LFxuICAgICAgMjI0LFxuICAgICAgMTMxLFxuICAgICAgMTU3LFxuICAgICAgNzMsXG4gICAgICAyMDQsXG4gICAgICAyNTUsXG4gICAgICAxNzQsXG4gICAgICAxODgsXG4gICAgICA1NyxcbiAgICAgIDQwLFxuICAgICAgMTQ0LFxuICAgICAgMTkyLFxuICAgICAgNDIsXG4gICAgICAxNzAsXG4gICAgICAxMDgsXG4gICAgICA4OVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAyNTAsXG4gICAgICA1OCxcbiAgICAgIDIwNCxcbiAgICAgIDIxOSxcbiAgICAgIDEwNSxcbiAgICAgIDIsXG4gICAgICAxMzAsXG4gICAgICAxMzEsXG4gICAgICA0OSxcbiAgICAgIDE4MyxcbiAgICAgIDE5LFxuICAgICAgODAsXG4gICAgICAxOSxcbiAgICAgIDIwNyxcbiAgICAgIDE2NCxcbiAgICAgIDIxOSxcbiAgICAgIDE2NCxcbiAgICAgIDk3LFxuICAgICAgMTE3LFxuICAgICAgMjFcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiRDdYRFRNWlBcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjk0NzI0ODMxODA5OjFAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjEwOTEyMjgzODEzMDgwNToxQGxpZFwiLFxuICAgIFwibmFtZVwiOiBcIvCfmYJcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNPTEE1Y0FERVBtdjRMMEdHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIk13U2FFYUpaZm5IN25TNlJWT1F5S2h4Vlc0UC9aeUZ0Y2dvQXlXYVp6bW89XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiTUFLUHZRUkdSbVN4aE9UQ2tsZmdvOXI2TGxTR1M5OWlrS0Urd2R4cU9ZTlFEV1VUTXFpNzZMVWpKRG5aOFEyRitET09sbjlQc0hjc3RBa3hkblY4QkE9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiZklxL0NtcUE3aGwva1VkWGl1Q3BQbzdzekhTSzNJZTBoZ25LWFlsNUVmZTh1N3FHOHRyY3U0R3FuTXVkaDhETTZEYXhoMktYYUt0WTZOODhOSnBJQ3c9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiOTQ3MjQ4MzE4MDk6MUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDUxLFxuICAgICAgICAgIDQsXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDE3LFxuICAgICAgICAgIDE2MixcbiAgICAgICAgICA4OSxcbiAgICAgICAgICAxMjYsXG4gICAgICAgICAgMTEzLFxuICAgICAgICAgIDI1MSxcbiAgICAgICAgICAxNTcsXG4gICAgICAgICAgNDYsXG4gICAgICAgICAgMTQ1LFxuICAgICAgICAgIDg0LFxuICAgICAgICAgIDIyOCxcbiAgICAgICAgICA1MCxcbiAgICAgICAgICA0MixcbiAgICAgICAgICAyOCxcbiAgICAgICAgICA4NSxcbiAgICAgICAgICA5MSxcbiAgICAgICAgICAxMzEsXG4gICAgICAgICAgMjU1LFxuICAgICAgICAgIDEwMyxcbiAgICAgICAgICAzMyxcbiAgICAgICAgICAxMDksXG4gICAgICAgICAgMTE0LFxuICAgICAgICAgIDEwLFxuICAgICAgICAgIDAsXG4gICAgICAgICAgMjAxLFxuICAgICAgICAgIDEwMixcbiAgICAgICAgICAxNTMsXG4gICAgICAgICAgMjA2LFxuICAgICAgICAgIDEwNlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzQwMTE4MDEzLFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBSmIxXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFKYjEuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJnLzVCUG1CSlUxc0hQTWRwcFFHdXBGWlgzK3RzNy9zeWppZjZudHp3bDBJPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjk0MTE4NzE3MCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzQwMTE4MDE0NDY3XCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "public",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
